<x-guest-layout title="ورود به حساب کاربری">
    <div class="mb-6 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary-50 text-primary"><x-heroicon-o-device-phone-mobile class="h-7 w-7" /></span><h1 class="mt-4 text-xl font-black text-slate-900">ورود با شماره موبایل</h1><p class="mt-2 text-xs text-slate-500">برای ورود، شماره موبایل و رمز عبور خود را وارد کنید.</p></div>
    <x-auth-session-status class="mb-4" :status="session('status')" />
    <form method="POST" action="{{ route('login') }}" class="space-y-5">@csrf
        <div><x-input-label for="login" value="شماره موبایل" /><x-text-input id="login" class="mt-2 block w-full" type="tel" name="login" :value="old('login', old('email'))" required autofocus autocomplete="tel" inputmode="tel" dir="ltr" placeholder="09120000000" /><x-input-error :messages="$errors->get('login')" class="mt-2" /></div>
        <div><div class="flex items-center justify-between"><x-input-label for="password" value="رمز عبور" />@if ($registrationMode !== 'mobile' && Route::has('password.request'))<a class="text-xs font-bold text-primary hover:text-primary-600" href="{{ route('password.request') }}">رمز عبور را فراموش کرده‌اید؟</a>@endif</div><x-text-input id="password" class="mt-2 block w-full" type="password" name="password" required autocomplete="current-password" /><x-input-error :messages="$errors->get('password')" class="mt-2" /></div>
        <label for="remember_me" class="flex items-center gap-2 text-xs font-bold text-slate-500"><input id="remember_me" type="checkbox" class="rounded border-slate-300 text-primary shadow-sm focus:ring-primary" name="remember"><span>مرا به خاطر بسپار</span></label>
        <button class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-black text-white transition hover:bg-primary-600"><x-heroicon-o-arrow-left-on-rectangle class="h-5 w-5" />ورود به حساب</button>
    </form>
    <div class="mt-6 border-t border-slate-100 pt-5 text-center text-xs text-slate-500">حساب کاربری ندارید؟ <a href="{{ route('register') }}" class="font-black text-primary hover:text-primary-600">ثبت‌نام با موبایل</a></div>
</x-guest-layout>
