<x-app-layout title="داشبورد من">
    <x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-xl font-black text-neutral">داشبورد من</h1><span class="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{{ auth()->user()->name }}</span></div></x-slot>
    <section class="space-y-5 px-4 py-6">
        <div class="rounded-2xl bg-primary p-5 text-white shadow-sm"><p class="text-sm text-white/80">مدیریت آگهی‌های شما</p><h2 class="mt-1 text-2xl font-black">همه‌چیز مرتب و آماده فروش</h2><a href="{{ route('listings.create') }}" class="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-bold text-primary">ثبت آگهی جدید</a></div>
        <div class="grid grid-cols-2 gap-3">@foreach (['pending' => ['در انتظار', 'text-warning'], 'approved' => ['تأییدشده', 'text-success'], 'rejected' => ['ردشده', 'text-error'], 'sold' => ['فروخته‌شده', 'text-info'], 'expired' => ['منقضی‌شده', 'text-slate-500']] as $key => [$label, $color])<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-2xl bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-black {{ $color }}">{{ $counts->get($key, 0) }}</p></a>@endforeach</div>
        <div class="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm text-xs font-bold whitespace-nowrap"><a href="{{ route('dashboard') }}" class="rounded-xl px-3 py-2 {{ ! $status ? 'bg-neutral text-white' : 'text-slate-500' }}">همه</a>@foreach (['pending' => 'در انتظار', 'approved' => 'تأییدشده', 'rejected' => 'ردشده', 'sold' => 'فروخته‌شده', 'expired' => 'منقضی‌شده'] as $key => $label)<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-xl px-3 py-2 {{ $status === $key ? 'bg-neutral text-white' : 'text-slate-500' }}">{{ $label }}</a>@endforeach</div>
        <div class="space-y-3">@forelse ($listings as $listing)<article class="rounded-2xl bg-white p-4 shadow-sm"><div class="flex gap-3">@if ($listing->primaryImage)<img src="{{ asset('storage/'.($listing->primaryImage->thumbnail_path ?: $listing->primaryImage->path)) }}" alt="{{ $listing->title }}" class="h-20 w-20 shrink-0 rounded-xl object-cover">@else<div class="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-primary-50 text-primary"><x-heroicon-o-device-phone-mobile class="h-8 w-8" /></div>@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><h2 class="truncate font-bold text-neutral">{{ $listing->title }}</h2><span class="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{{ $listing->status->label() }}</span></div><p class="mt-2 text-xs text-slate-500">{{ $listing->brand->name }} · {{ $listing->phoneModel->name }}</p><p class="mt-2 text-sm font-black text-primary">{{ number_format($listing->price) }} تومان</p></div></div><div class="mt-3 flex gap-2">@if (in_array($listing->status->value, ['pending', 'rejected'], true))<a href="{{ route('listings.edit', $listing) }}" class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ویرایش</a>@endif @if ($listing->status->value === 'expired')<form method="POST" action="{{ route('listings.renew', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ارسال مجدد</button></form>@endif @if ($listing->status->value === 'approved')<form method="POST" action="{{ route('listings.sold', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-secondary/10 px-3 py-2 text-xs font-bold text-success">فروخته شد</button></form>@endif<form method="POST" action="{{ route('listings.destroy', $listing) }}" onsubmit="return confirm('آگهی حذف شود؟')">@csrf @method('DELETE')<button class="rounded-lg bg-error/10 px-3 py-2 text-xs font-bold text-error">حذف</button></form></div></article>@empty<div class="rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center text-sm text-slate-500">در این وضعیت آگهی‌ای ندارید.</div>@endforelse</div>
        {{ $listings->links() }}
    </section>
</x-app-layout>
