<x-app-layout title="داشبورد من">
    <x-slot name="header"><div class="flex items-center justify-between gap-3"><div><p class="text-xs font-bold text-primary">حساب کاربری</p><h1 class="mt-1 text-xl font-black text-neutral">داشبورد من</h1></div><span class="max-w-[140px] truncate rounded-full bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary">{{ auth()->user()->name }}</span></div></x-slot>
    <section class="space-y-6 px-4 py-6">
        @if (session('status'))
            <div class="flex items-center gap-2 rounded-lg border border-secondary/20 bg-secondary/10 p-4 text-sm font-bold text-success" role="status"><x-heroicon-o-check-circle class="h-5 w-5 shrink-0" />{{ session('status') }}</div>
        @endif
        @if ($errors->any())
            <div class="flex items-start gap-2 rounded-lg border border-error/20 bg-error/10 p-4 text-sm font-bold text-error" role="alert"><x-heroicon-o-exclamation-triangle class="h-5 w-5 shrink-0" /><span>{{ $errors->first() }}</span></div>
        @endif
        <div class="relative overflow-hidden rounded-lg bg-primary p-5 text-white shadow-lg shadow-primary/15"><div class="absolute -left-8 -top-10 h-32 w-32 rounded-full bg-white/10 blur-2xl"></div><div class="relative"><p class="text-sm text-white/75">مدیریت آگهی‌های شما</p><h2 class="mt-1 text-2xl font-black">همه‌چیز مرتب و آماده فروش</h2><p class="mt-2 text-xs leading-6 text-white/75">وضعیت آگهی‌هایت را بررسی کن و سریع‌تر به خریدارها پاسخ بده.</p><a href="{{ route('listings.create') }}" class="mt-4 inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-black text-primary transition hover:bg-primary-50"><x-heroicon-o-plus class="h-5 w-5" />ثبت آگهی جدید</a></div></div>
        @if ($store)
            <div class="rounded-lg {{ $store->is_enabled ? 'bg-neutral text-white' : 'bg-slate-100 text-neutral' }} p-5 shadow-sm">
                <div class="flex items-start justify-between gap-3">
                    <div class="flex items-center gap-3">
                        <span class="flex h-11 w-11 items-center justify-center rounded-lg {{ $store->is_enabled ? 'bg-primary text-white' : 'bg-warning/15 text-warning' }}"><x-heroicon-o-building-storefront class="h-6 w-6" /></span>
                        <div><p class="text-xs {{ $store->is_enabled ? 'text-white/60' : 'text-slate-500' }}">غرفه شما</p><h2 class="mt-1 font-black">{{ $store->name }}</h2></div>
                    </div>
                    <span class="rounded-full px-3 py-1.5 text-[10px] font-black {{ $store->is_admin_disabled ? 'bg-error/15 text-error' : ($store->is_enabled ? 'bg-success/15 text-success' : 'bg-warning/15 text-warning') }}">{{ $store->is_admin_disabled ? 'غیرفعال توسط مدیریت' : ($store->is_enabled ? 'فعال و قابل مشاهده' : 'غیرفعال') }}</span>
                </div>
                <p class="mt-4 rounded-lg {{ $store->is_enabled ? 'bg-white/10 text-white/70' : 'bg-white text-slate-500' }} px-3 py-2 text-left text-xs" dir="ltr">/store/{{ $store->slug }}</p>
                <div class="mt-4 flex flex-wrap gap-2">
                    @if ($store->isPubliclyEnabled())<a href="{{ route('storefront.show', $store) }}" class="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2.5 text-xs font-black text-neutral"><x-heroicon-o-arrow-top-right-on-square class="h-4 w-4" />مشاهده غرفه</a>@endif
                    <a href="{{ route('storefront.edit') }}" class="inline-flex items-center gap-2 rounded-lg {{ $store->is_enabled ? 'bg-white/10 text-white hover:bg-white/15' : 'bg-neutral text-white' }} px-4 py-2.5 text-xs font-bold"><x-heroicon-o-pencil-square class="h-4 w-4" />ویرایش اطلاعات</a>
                </div>
            </div>
        @else
            <a href="{{ route('storefront.edit') }}" class="flex items-center justify-between rounded-lg border border-dashed border-primary/30 bg-primary-50 p-5 text-primary transition hover:border-primary"><span><strong class="block font-black">غرفه خودت را بساز</strong><small class="mt-1 block text-xs text-primary/70">آگهی‌هایت را در یک صفحه اختصاصی به خریدارها نمایش بده.</small></span><x-heroicon-o-building-storefront class="h-7 w-7" /></a>
        @endif
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">@foreach (['pending' => ['در انتظار', 'text-warning', 'bg-warning/10'], 'approved' => ['تأییدشده', 'text-success', 'bg-success/10'], 'rejected' => ['ردشده', 'text-error', 'bg-error/10'], 'sold' => ['فروخته‌شده', 'text-info', 'bg-info/10'], 'expired' => ['منقضی‌شده', 'text-slate-500', 'bg-slate-100']] as $key => [$label, $color, $background])<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-lg bg-white p-4 shadow-sm border border-slate-200 transition hover:-translate-y-0.5 hover:shadow-md"><span class="flex h-9 w-9 items-center justify-center rounded-lg {{ $background }} {{ $color }}"><x-heroicon-o-chart-bar class="h-5 w-5" /></span><p class="mt-3 text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-1 text-2xl font-black {{ $color }}">{{ number_format($counts->get($key, 0)) }}</p></a>@endforeach</div>
        <div class="flex items-center justify-between"><div><h2 class="text-lg font-black text-neutral">آگهی‌های من</h2><p class="mt-1 text-xs text-slate-400">آگهی‌ها را بر اساس وضعیت مدیریت کن.</p></div><a href="{{ route('listings.index') }}" class="text-xs font-bold text-primary">جستجوی آگهی‌ها</a></div>
        <div class="flex gap-2 overflow-x-auto rounded-lg bg-white p-2 shadow-sm border border-slate-200 text-xs font-bold whitespace-nowrap"><a href="{{ route('dashboard') }}" class="rounded-lg px-3 py-2 {{ ! $status ? 'bg-neutral text-white' : 'text-slate-500 hover:bg-slate-50' }}">همه</a>@foreach (['pending' => 'در انتظار', 'approved' => 'تأییدشده', 'rejected' => 'ردشده', 'sold' => 'فروخته‌شده', 'expired' => 'منقضی‌شده'] as $key => $label)<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-lg px-3 py-2 {{ $status === $key ? 'bg-neutral text-white' : 'text-slate-500 hover:bg-slate-50' }}">{{ $label }}</a>@endforeach</div>
        <div class="space-y-3">@forelse ($listings as $listing)<article class="rounded-lg bg-white p-4 shadow-sm border border-slate-200"><div class="flex gap-3">@if ($listing->primaryImage)<img src="{{ asset('storage/'.($listing->primaryImage->thumbnail_path ?: $listing->primaryImage->path)) }}" alt="{{ $listing->title }}" class="h-20 w-20 shrink-0 rounded-lg object-cover" loading="lazy" decoding="async">@else<img src="{{ asset('images/listing-placeholder.svg') }}" alt="تصویر پیش‌فرض آگهی" class="h-20 w-20 shrink-0 rounded-lg object-cover" loading="lazy" decoding="async">@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><h2 class="truncate font-black text-neutral">{{ $listing->title }}</h2><span class="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{{ $listing->status->label() }}</span></div><p class="mt-2 text-xs text-slate-500">{{ $listing->brand->name }} · {{ $listing->phoneModel->name }}</p><p class="mt-2 text-sm font-black text-primary">{{ $listing->price_on_request ? 'تماس بگیرید' : number_format($listing->price).' تومان' }}</p></div></div><div class="mt-4 flex flex-wrap gap-2">@if (in_array($listing->status->value, ['pending', 'rejected'], true))<a href="{{ route('listings.edit', $listing) }}" class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ویرایش</a>@endif @if ($listing->status->value === 'expired')<form method="POST" action="{{ route('listings.renew', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ارسال مجدد</button></form>@endif @if ($listing->status->value === 'approved')<form method="POST" action="{{ route('listings.sold', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-secondary/10 px-3 py-2 text-xs font-bold text-success">فروخته شد</button></form>@endif<form method="POST" action="{{ route('listings.destroy', $listing) }}" onsubmit="return confirm('آگهی حذف شود؟')">@csrf @method('DELETE')<button class="rounded-lg bg-error/10 px-3 py-2 text-xs font-bold text-error">حذف</button></form></div></article>@empty<div class="rounded-lg border border-dashed border-slate-200 bg-white p-10 text-center shadow-sm"><x-heroicon-o-rectangle-stack class="mx-auto h-12 w-12 text-primary/30" /><h3 class="mt-4 font-black text-neutral">در این وضعیت آگهی‌ای ندارید</h3><p class="mt-2 text-xs leading-6 text-slate-500">اولین آگهی خودت را ثبت کن و آن را از همین‌جا مدیریت کن.</p><a href="{{ route('listings.create') }}" class="mt-4 inline-flex rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-white">ثبت آگهی</a></div>@endforelse</div>
        {{ $listings->links() }}
    </section>
</x-app-layout>
