<x-app-layout title="داشبورد من">
    <x-slot name="header"><div class="flex items-center justify-between gap-3"><div><p class="text-xs font-bold text-primary">حساب کاربری</p><h1 class="mt-1 text-xl font-black text-neutral">داشبورد من</h1></div><span class="max-w-[140px] truncate rounded-full bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary">{{ auth()->user()->name }}</span></div></x-slot>
    <section class="space-y-6 px-4 py-6">
        <div class="relative overflow-hidden rounded-3xl bg-primary p-5 text-white shadow-lg shadow-primary/15"><div class="absolute -left-8 -top-10 h-32 w-32 rounded-full bg-white/10 blur-2xl"></div><div class="relative"><p class="text-sm text-white/75">مدیریت آگهی‌های شما</p><h2 class="mt-1 text-2xl font-black">همه‌چیز مرتب و آماده فروش</h2><p class="mt-2 text-xs leading-6 text-white/75">وضعیت آگهی‌هایت را بررسی کن و سریع‌تر به خریدارها پاسخ بده.</p><a href="{{ route('listings.create') }}" class="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-black text-primary transition hover:bg-primary-50"><x-heroicon-o-plus class="h-5 w-5" />ثبت آگهی جدید</a></div></div>
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">@foreach (['pending' => ['در انتظار', 'text-warning', 'bg-warning/10'], 'approved' => ['تأییدشده', 'text-success', 'bg-success/10'], 'rejected' => ['ردشده', 'text-error', 'bg-error/10'], 'sold' => ['فروخته‌شده', 'text-info', 'bg-info/10'], 'expired' => ['منقضی‌شده', 'text-slate-500', 'bg-slate-100']] as $key => [$label, $color, $background])<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100 transition hover:-translate-y-0.5 hover:shadow-md"><span class="flex h-9 w-9 items-center justify-center rounded-xl {{ $background }} {{ $color }}"><x-heroicon-o-chart-bar class="h-5 w-5" /></span><p class="mt-3 text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-1 text-2xl font-black {{ $color }}">{{ number_format($counts->get($key, 0)) }}</p></a>@endforeach</div>
        <div class="flex items-center justify-between"><div><h2 class="text-lg font-black text-neutral">آگهی‌های من</h2><p class="mt-1 text-xs text-slate-400">آگهی‌ها را بر اساس وضعیت مدیریت کن.</p></div><a href="{{ route('listings.index') }}" class="text-xs font-bold text-primary">جستجوی آگهی‌ها</a></div>
        <div class="flex gap-2 overflow-x-auto rounded-2xl bg-white p-2 shadow-sm ring-1 ring-slate-100 text-xs font-bold whitespace-nowrap"><a href="{{ route('dashboard') }}" class="rounded-xl px-3 py-2 {{ ! $status ? 'bg-neutral text-white' : 'text-slate-500 hover:bg-slate-50' }}">همه</a>@foreach (['pending' => 'در انتظار', 'approved' => 'تأییدشده', 'rejected' => 'ردشده', 'sold' => 'فروخته‌شده', 'expired' => 'منقضی‌شده'] as $key => $label)<a href="{{ route('dashboard', ['status' => $key]) }}" class="rounded-xl px-3 py-2 {{ $status === $key ? 'bg-neutral text-white' : 'text-slate-500 hover:bg-slate-50' }}">{{ $label }}</a>@endforeach</div>
        <div class="space-y-3">@forelse ($listings as $listing)<article class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100"><div class="flex gap-3">@if ($listing->primaryImage)<img src="{{ asset('storage/'.($listing->primaryImage->thumbnail_path ?: $listing->primaryImage->path)) }}" alt="{{ $listing->title }}" class="h-20 w-20 shrink-0 rounded-xl object-cover">@else<div class="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-primary-50 text-primary"><x-heroicon-o-device-phone-mobile class="h-8 w-8" /></div>@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><h2 class="truncate font-black text-neutral">{{ $listing->title }}</h2><span class="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{{ $listing->status->label() }}</span></div><p class="mt-2 text-xs text-slate-500">{{ $listing->brand->name }} · {{ $listing->phoneModel->name }}</p><p class="mt-2 text-sm font-black text-primary">{{ number_format($listing->price) }} تومان</p></div></div><div class="mt-4 flex flex-wrap gap-2">@if (in_array($listing->status->value, ['pending', 'rejected'], true))<a href="{{ route('listings.edit', $listing) }}" class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ویرایش</a>@endif @if ($listing->status->value === 'expired')<form method="POST" action="{{ route('listings.renew', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-primary/10 px-3 py-2 text-xs font-bold text-primary">ارسال مجدد</button></form>@endif @if ($listing->status->value === 'approved')<form method="POST" action="{{ route('listings.sold', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-secondary/10 px-3 py-2 text-xs font-bold text-success">فروخته شد</button></form>@endif<form method="POST" action="{{ route('listings.destroy', $listing) }}" onsubmit="return confirm('آگهی حذف شود؟')">@csrf @method('DELETE')<button class="rounded-lg bg-error/10 px-3 py-2 text-xs font-bold text-error">حذف</button></form></div></article>@empty<div class="rounded-3xl border border-dashed border-slate-200 bg-white p-10 text-center shadow-sm"><x-heroicon-o-rectangle-stack class="mx-auto h-12 w-12 text-primary/30" /><h3 class="mt-4 font-black text-neutral">در این وضعیت آگهی‌ای ندارید</h3><p class="mt-2 text-xs leading-6 text-slate-500">اولین آگهی خودت را ثبت کن و آن را از همین‌جا مدیریت کن.</p><a href="{{ route('listings.create') }}" class="mt-4 inline-flex rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-white">ثبت آگهی</a></div>@endforelse</div>
        {{ $listings->links() }}
    </section>
</x-app-layout>
