<x-app-layout title="خانه">
    <section x-data="pullToRefresh()" @touchstart.passive="touchStart($event)" @touchmove.passive="touchMove($event)" @touchend="touchEnd()" class="relative space-y-7 px-4 py-6">
        <div x-cloak x-show="distance > 0 || refreshing" class="pointer-events-none fixed inset-x-0 top-2 z-40 mx-auto flex max-w-md justify-center" aria-live="polite">
            <span class="rounded-full bg-white px-4 py-2 text-xs font-bold text-primary shadow-lg ring-1 ring-primary/10" x-text="refreshing ? 'در حال تازه‌سازی...' : 'برای تازه‌سازی رها کنید'"></span>
        </div>
        <div class="relative overflow-hidden rounded-[2rem] bg-slate-900 p-6 text-white shadow-xl shadow-slate-900/10 sm:p-8">
            <div class="absolute -left-16 -top-16 h-44 w-44 rounded-full bg-primary/20 blur-3xl"></div><div class="absolute -bottom-20 right-0 h-48 w-48 rounded-full bg-secondary/10 blur-3xl"></div>
            <div class="relative"><span class="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-[11px] font-bold text-primary-100"><x-heroicon-o-shield-check class="h-4 w-4" /> بازار مطمئن موبایل</span><h1 class="mt-5 text-3xl font-black leading-[1.35] sm:text-4xl">گوشی بعدی‌ات<br><span class="text-primary">همین‌جاست.</span></h1><p class="mt-3 max-w-sm text-sm leading-7 text-white/65">از بین آگهی‌های واقعی موبایل، مدل مناسب خودت را سریع و مطمئن پیدا کن.</p>
                <div class="relative mt-6" x-data="searchSuggest('{{ route('listings.autocomplete') }}')" @click.outside="open = false"><form action="{{ route('listings.index') }}" method="GET" class="flex flex-col gap-2 sm:flex-row"><label class="relative flex-1"><span class="sr-only">جستجوی آگهی</span><x-heroicon-o-magnifying-glass class="pointer-events-none absolute right-3 top-3 h-5 w-5 text-slate-400" /><input name="q" x-model="query" @input.debounce.300ms="search" @focus="open = suggestions.length > 0" type="search" autocomplete="off" placeholder="مثلاً آیفون ۱۳ یا سامسونگ" class="w-full rounded-xl border-0 bg-white py-3.5 pe-10 ps-3 text-sm text-neutral placeholder:text-slate-400 focus:ring-2 focus:ring-primary"></label><button type="submit" class="rounded-xl bg-primary px-5 py-3.5 text-sm font-black text-white transition hover:bg-primary-600">جستجوی آگهی‌ها</button></form><div x-cloak x-show="open && (loading || suggestions.length)" class="absolute inset-x-0 top-full z-20 mt-2 overflow-hidden rounded-2xl bg-white text-neutral shadow-2xl"><div x-show="loading" class="px-4 py-3 text-xs text-slate-500">در حال جستجو...</div><template x-for="suggestion in suggestions" :key="suggestion.url"><a :href="suggestion.url" class="flex items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-0 hover:bg-primary-50"><template x-if="suggestion.image"><img :src="suggestion.image" :alt="suggestion.title" class="h-11 w-11 rounded-xl object-cover"></template><template x-if="!suggestion.image"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-primary-50 text-primary"><x-heroicon-o-device-phone-mobile class="h-5 w-5" /></span></template><span class="min-w-0"><span class="block truncate text-sm font-bold" x-text="suggestion.title"></span><span class="mt-1 block truncate text-xs text-slate-500" x-text="suggestion.meta"></span></span></a></template></div></div>
            </div>
        </div>

        <div x-data='homeSearch(@js(url("/locations/provinces")), @js(route("listings.search.suggestions")))' class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100">
            <div class="mb-4"><p class="text-xs font-bold text-primary">جستجوی نزدیک‌تر</p><h2 class="mt-1 text-lg font-black text-neutral">در کدام استان و شهر هستید؟</h2><p class="mt-1 text-xs leading-6 text-slate-400">موقعیت و مدل گوشی را انتخاب کنید تا سریع‌تر به آگهی مناسب برسید.</p></div>
            <form method="GET" action="{{ route('listings.index') }}" class="space-y-3">
                <div class="grid grid-cols-2 gap-2">
                    <div><label for="home-province" class="mb-1.5 block text-xs font-bold text-slate-600">استان</label><select id="home-province" name="province_id" x-model="provinceId" @change="loadCities" class="w-full rounded-xl border-0 bg-slate-50 text-sm ring-1 ring-slate-100 focus:ring-primary"><option value="">همه استان‌ها</option>@foreach ($provinces as $province)<option value="{{ $province->id }}">{{ $province->name }}</option>@endforeach</select></div>
                    <div><label for="home-city" class="mb-1.5 block text-xs font-bold text-slate-600">شهر</label><select id="home-city" name="city_id" x-model="cityId" :disabled="!provinceId || citiesLoading" class="w-full rounded-xl border-0 bg-slate-50 text-sm ring-1 ring-slate-100 focus:ring-primary"><option value="">همه شهرها</option><template x-for="city in cities" :key="city.id"><option :value="city.id" x-text="city.name"></option></template></select></div>
                </div>
                <div class="relative" @click.outside="open = false"><label for="home-search" class="mb-1.5 block text-xs font-bold text-slate-600">دنبال چه چیزی هستید؟</label><input id="home-search" name="q" x-model="query" @input="search" @focus="query.length >= 2 && (open = true)" @keydown.escape="open = false" type="search" autocomplete="off" placeholder="مثلاً آیفون یا iPhone 13" class="w-full rounded-xl border-0 bg-slate-50 py-3 px-3 text-sm ring-1 ring-slate-100 focus:ring-primary"><input type="hidden" name="brand_id" x-model="selectedBrandId"><input type="hidden" name="phone_model_id" x-model="selectedModelId"><div x-show="open" x-cloak class="absolute inset-x-0 top-full z-20 mt-2 max-h-72 overflow-y-auto rounded-2xl bg-white p-2 shadow-xl ring-1 ring-slate-100"><div x-show="loading" class="px-3 py-3 text-xs text-slate-500">در حال جستجو...</div><template x-if="!loading && suggestions.brands.length"><div><p class="px-3 pb-1 pt-2 text-[11px] font-bold text-slate-400">برندها</p><template x-for="brand in suggestions.brands" :key="`home-brand-${brand.id}`"><button type="button" @click="selectBrand(brand)" class="flex w-full items-center justify-between rounded-xl px-3 py-2 text-right text-sm hover:bg-primary-50"><span x-text="brand.label" class="font-bold text-neutral"></span><span x-text="brand.secondary" class="text-xs text-slate-400"></span></button></template></div></template><template x-if="!loading && suggestions.models.length"><div><p class="px-3 pb-1 pt-2 text-[11px] font-bold text-slate-400">مدل‌ها</p><template x-for="model in suggestions.models" :key="`home-model-${model.id}`"><button type="button" @click="selectModel(model)" class="flex w-full items-center justify-between gap-3 rounded-xl px-3 py-2 text-right text-sm hover:bg-primary-50"><span><span x-text="model.label" class="font-bold text-neutral"></span><span x-text="model.brand ? ` · ${model.brand}` : ''" class="mr-1 text-xs text-slate-400"></span></span><span x-text="model.secondary" class="text-xs text-slate-400"></span></button></template></div></template><div x-show="!loading && !suggestions.brands.length && !suggestions.models.length" class="px-3 py-3 text-xs text-slate-500">موردی پیدا نشد.</div></div></div>
                <button class="mobile-button w-full bg-primary text-white hover:bg-primary-600"><x-heroicon-o-magnifying-glass class="h-5 w-5" />جستجوی آگهی‌ها</button>
            </form>
        </div>

        <div class="grid grid-cols-3 gap-2 rounded-2xl border border-slate-100 bg-white p-3 shadow-sm"><div class="flex flex-col items-center gap-1 text-center"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-success/10 text-success"><x-heroicon-o-check-badge class="h-5 w-5" /></span><span class="text-[10px] font-bold text-slate-600">آگهی بررسی‌شده</span></div><div class="flex flex-col items-center gap-1 border-x border-slate-100 text-center"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-info/10 text-info"><x-heroicon-o-sparkles class="h-5 w-5" /></span><span class="text-[10px] font-bold text-slate-600">جستجوی هوشمند</span></div><div class="flex flex-col items-center gap-1 text-center"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><x-heroicon-o-lock-closed class="h-5 w-5" /></span><span class="text-[10px] font-bold text-slate-600">خرید امن‌تر</span></div></div>

        <div><div class="mb-3 flex items-center justify-between"><div><h2 class="text-lg font-black text-neutral">دسته‌های محبوب</h2><p class="mt-1 text-xs text-slate-400">سریع‌تر به مدل موردنظرت برس</p></div><a href="{{ route('listings.index') }}" class="text-xs font-bold text-primary">مشاهده همه</a></div><div class="grid grid-cols-3 gap-3">@foreach ([['آیفون', 'bg-slate-900'], ['سامسونگ', 'bg-blue-600'], ['شیائومی', 'bg-orange-500']] as [$brand, $color])<a href="{{ route('listings.index', ['q' => $brand]) }}" class="group rounded-2xl bg-white p-3 text-center shadow-sm ring-1 ring-slate-100 transition hover:-translate-y-1 hover:shadow-md"><div class="mx-auto mb-2 flex h-11 w-11 items-center justify-center rounded-2xl {{ $color }} text-white transition group-hover:scale-105"><x-heroicon-o-device-phone-mobile class="h-6 w-6" /></div><span class="text-xs font-black text-neutral">{{ $brand }}</span></a>@endforeach</div></div>

        <div><div class="mb-3 flex items-center justify-between"><div><h2 class="text-lg font-black text-neutral">آخرین آگهی‌ها</h2><p class="mt-1 text-xs text-slate-400">تازه‌ترین فرصت‌های خرید موبایل</p></div><a href="{{ route('listings.index') }}" class="text-xs font-bold text-primary">مشاهده همه</a></div><div class="grid grid-cols-2 gap-3">@forelse ($latestListings as $listing)<x-listing-card :listing="$listing" />@empty<div class="col-span-2 rounded-2xl bg-white p-6 text-center text-sm text-slate-500">هنوز آگهی تأییدشده‌ای ثبت نشده است.</div>@endforelse</div></div>

        <div class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div class="flex items-center gap-3"><div class="rounded-xl bg-secondary/10 p-3 text-secondary"><x-heroicon-o-shield-check class="h-6 w-6" /></div><div><h3 class="font-bold text-neutral">خرید و فروش امن‌تر</h3><p class="mt-1 text-xs leading-6 text-slate-500">آگهی‌ها پیش از انتشار توسط تیم ما بررسی می‌شوند تا تجربه مطمئن‌تری داشته باشید.</p></div></div></div>
    </section>
</x-app-layout>
