<x-app-layout title="ویرایش آگهی">
    <x-slot name="header"><div class="flex items-center gap-3"><a href="{{ route('dashboard') }}" class="rounded-lg bg-slate-100 p-2 text-slate-500 transition hover:bg-primary-50 hover:text-primary"><x-heroicon-o-arrow-right class="h-5 w-5" /></a><div><p class="text-xs font-bold text-primary">مدیریت آگهی</p><h1 class="mt-1 text-xl font-black text-neutral">ویرایش آگهی</h1></div></div></x-slot>
    <section x-data="listingWizard()" data-models-endpoint="{{ url('/listings/models') }}" data-cities-endpoint="{{ url('/locations/provinces') }}" data-initial-brand-id="{{ old('brand_id', $listing->brand_id) }}" data-initial-model-id="{{ old('phone_model_id', $listing->phone_model_id) }}" data-initial-province-id="{{ old('province_id', $listing->province_id) }}" data-initial-city-id="{{ old('city_id', $listing->city_id) }}" class="space-y-5 px-4 py-6">
        <script type="application/json" data-listing-initial-attributes>@json($initialModelAttributes)</script>
        <script type="application/json" data-listing-initial-values>@json(old('attributes', $initialValues))</script>
        @if ($errors->any())<x-flowbite-alert type="danger"><ul class="space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-flowbite-alert>@endif
        <div class="flex items-start gap-3 rounded-lg border border-warning/20 bg-warning/10 p-4 text-xs leading-6 text-neutral"><x-heroicon-o-information-circle class="mt-0.5 h-5 w-5 shrink-0 text-warning" /><span>با ذخیره تغییرات، آگهی دوباره برای بررسی ادمین ارسال می‌شود.</span></div>
        @if ($listing->status->value === 'rejected' && $listing->rejection_reason)
            <x-flowbite-alert type="danger">
                <p class="font-black">علت رد آگهی</p>
                <p class="mt-1 font-normal leading-6">{{ $listing->rejection_reason }}</p>
            </x-flowbite-alert>
        @endif
        <form method="POST" action="{{ route('listings.update', $listing) }}" enctype="multipart/form-data" class="space-y-4 rounded-lg bg-white p-5 shadow-sm border border-slate-200">
            @csrf @method('PUT')
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-sm font-bold text-neutral">برند</label><select name="brand_id" data-listing-brand-picker data-model-target="#public-edit-listing-model" data-models-endpoint="{{ url('/listings/models') }}" x-model="brandId" @change="loadModels()" required class="public-select"><option value="">انتخاب برند</option>@foreach ($brands as $brand)<option value="{{ $brand->id }}" @selected((string) old('brand_id', $listing->brand_id) === (string) $brand->id)>{{ $brand->name }} ({{ $brand->name_en }})</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-bold text-neutral">مدل گوشی</label><select id="public-edit-listing-model" name="phone_model_id" x-model="modelId" @change="loadAttributes" required :disabled="!brandId || modelsLoading" class="public-select"><option value="" x-text="modelsLoading ? 'در حال بارگذاری مدل‌ها...' : 'انتخاب مدل'"></option><template x-for="model in models" :key="model.id"><option :value="model.id" x-text="`${model.label || model.name_fa || model.name} — ${model.secondary || model.name_en || model.name}`"></option></template></select><p class="mt-1 text-xs text-slate-400">فقط مدل‌های برند انتخاب‌شده نمایش داده می‌شوند.</p></div></div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">عنوان آگهی</label><input name="title" value="{{ old('title', $listing->title) }}" required class="block w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30"></div>
            <div x-data="{ priceOnRequest: @js((bool) old('price_on_request', $listing->price_on_request)) }"><label class="mb-2 block text-sm font-bold text-neutral">قیمت (تومان)</label><input x-show="!priceOnRequest" name="price" value="{{ old('price', $listing->price) }}" :required="!priceOnRequest" type="number" min="0" class="w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30">@if ($allowContactPrice)<label class="mt-3 flex cursor-pointer items-center gap-2 text-sm font-bold text-neutral"><input type="checkbox" name="price_on_request" value="1" x-model="priceOnRequest" @checked(old('price_on_request', $listing->price_on_request)) class="public-check"> قیمت را اعلام نمی‌کنم؛ تماس بگیرید</label>@endif</div>
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-sm font-bold text-neutral">استان</label><select name="province_id" x-model="provinceId" @change="loadCities" class="public-select"><option value="">انتخاب استان</option>@foreach($provinces as $province)<option value="{{ $province->id }}">{{ $province->name }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-bold text-neutral">شهر</label><select name="city_id" x-model="cityId" :disabled="!provinceId || citiesLoading" class="public-select"><option value="">انتخاب شهر</option><template x-for="city in cities" :key="city.id"><option :value="city.id" x-text="city.name"></option></template></select></div></div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">توضیحات</label><textarea name="description" rows="4" class="block w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30">{{ old('description', $listing->description) }}</textarea></div>
            <div x-data='imagePicker(@js($maxImageUploadMb), {{ max(0, $maxImageUploadCount - $listing->images->count()) }})'><label class="mb-2 block text-sm font-bold text-neutral">افزودن تصاویر <span class="text-xs font-normal text-slate-400">حداکثر {{ \App\Support\PersianNumber::digits($maxImageUploadCount) }} تصویر، هر تصویر {{ $maxImageUploadMb }} مگابایت</span></label><label class="flex cursor-pointer items-center gap-3 rounded-lg border-2 border-dashed border-primary/20 bg-primary-50/40 p-4 transition hover:border-primary/50"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-white text-primary shadow-sm"><x-heroicon-o-photo class="h-5 w-5" /></span><span class="text-xs font-bold text-slate-600">برای افزودن تصاویر کلیک کنید<input @change="select($event)" type="file" name="images[]" multiple accept=".jpg,.jpeg,.png,.webp" class="sr-only"></span></label><div x-show="previews.length" x-cloak class="mt-3 grid grid-cols-4 gap-2"><template x-for="preview in previews" :key="preview.url"><div class="overflow-hidden rounded-lg bg-slate-50 border border-slate-200"><img :src="preview.url" :alt="preview.name" class="h-20 w-full object-cover"><p x-text="preview.name" class="truncate px-1.5 py-1 text-[9px] text-slate-500"></p></div></template></div><div class="mt-2 flex items-center justify-between text-[10px] text-slate-400"><span x-show="previews.length" x-text="`${previews.length} تصویر جدید انتخاب شده`"></span><span>ظرفیت باقی‌مانده: {{ \App\Support\PersianNumber::digits(max(0, $maxImageUploadCount - $listing->images->count())) }} تصویر</span></div><p x-show="invalid" x-text="message" class="mt-2 rounded-lg bg-error/10 px-3 py-2 text-xs font-bold text-error"></p></div>
            @if ($listing->images->isNotEmpty())<div><h2 class="mb-2 text-sm font-bold text-neutral">تصاویر فعلی</h2><div class="grid grid-cols-3 gap-2">@foreach ($listing->images as $image)<div class="relative"><img src="{{ asset('storage/'.$image->path) }}" alt="{{ $listing->title }}" class="h-24 w-full rounded-lg object-cover" loading="lazy" decoding="async"><form method="POST" action="{{ route('listings.images.destroy', [$listing, $image]) }}" class="absolute left-1 top-1">@csrf @method('DELETE')<button class="rounded-full bg-error px-2 py-1 text-[10px] font-bold text-white">حذف</button></form></div>@endforeach</div></div>@endif
            <div class="border-t border-slate-100 pt-4"><div class="flex items-center justify-between gap-3"><div><h2 class="font-black text-neutral">مشخصات گوشی</h2><p class="mt-1 text-xs text-slate-400">هر ویژگی را جداگانه انتخاب کنید و مقدار آن را وارد کنید.</p></div><span x-show="attributesLoading" class="text-xs text-slate-400">در حال بارگذاری...</span></div><div class="mt-4"><x-listing-attribute-repeater :attribute-definitions="$initialModelAttributes" :values="old('attributes', $initialValues)" /></div><template x-if="false"><select class="public-select min-h-28"></select><input class="public-input"></template></div>
            <button type="submit" class="mobile-button w-full bg-primary text-white hover:bg-primary-600">ذخیره و ارسال برای بررسی</button>
        </form>
    </section>
</x-app-layout>
