<x-app-layout title="ویرایش آگهی">
    <x-slot name="header"><div class="flex items-center gap-3"><a href="{{ route('dashboard') }}" class="rounded-lg bg-slate-100 p-2 text-slate-500 transition hover:bg-primary-50 hover:text-primary"><x-heroicon-o-arrow-right class="h-5 w-5" /></a><div><p class="text-xs font-bold text-primary">مدیریت آگهی</p><h1 class="mt-1 text-xl font-black text-neutral">ویرایش آگهی</h1></div></div></x-slot>
    <section class="space-y-5 px-4 py-6">
        @if ($errors->any())<x-flowbite-alert type="danger"><ul class="space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-flowbite-alert>@endif
        <div class="flex items-start gap-3 rounded-lg border border-warning/20 bg-warning/10 p-4 text-xs leading-6 text-neutral"><x-heroicon-o-information-circle class="mt-0.5 h-5 w-5 shrink-0 text-warning" /><span>با ذخیره تغییرات، آگهی دوباره برای بررسی ادمین ارسال می‌شود.</span></div>
        <form method="POST" action="{{ route('listings.update', $listing) }}" enctype="multipart/form-data" class="space-y-4 rounded-lg bg-white p-5 shadow-sm border border-slate-200">
            @csrf @method('PUT')
            <div><label class="mb-2 block text-sm font-bold text-neutral">برند</label><select name="brand_id" required class="w-full rounded-lg border-slate-200 text-sm"><option value="">انتخاب برند</option>@foreach ($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id', $listing->brand_id) == $brand->id)>{{ $brand->name }} ({{ $brand->name_en }})</option>@endforeach</select></div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">مدل گوشی</label><select name="phone_model_id" required class="w-full rounded-lg border-slate-200 text-sm"><option value="">انتخاب مدل</option>@foreach ($brands as $brand)<optgroup label="{{ $brand->name }}">@foreach ($brand->phoneModels as $model)<option value="{{ $model->id }}" @selected(old('phone_model_id', $listing->phone_model_id) == $model->id)>{{ $model->name }}</option>@endforeach</optgroup>@endforeach</select></div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">عنوان آگهی</label><input name="title" value="{{ old('title', $listing->title) }}" required class="w-full rounded-lg border-slate-200 text-sm"></div>
            <div x-data="{ priceOnRequest: @js((bool) old('price_on_request', $listing->price_on_request)) }"><label class="mb-2 block text-sm font-bold text-neutral">قیمت (تومان)</label><input x-show="!priceOnRequest" name="price" value="{{ old('price', $listing->price) }}" :required="!priceOnRequest" type="number" min="0" class="w-full rounded-lg border-slate-200 text-sm">@if ($allowContactPrice)<label class="mt-3 flex cursor-pointer items-center gap-2 text-sm font-bold text-neutral"><input type="checkbox" name="price_on_request" value="1" x-model="priceOnRequest" @checked(old('price_on_request', $listing->price_on_request)) class="rounded border-slate-300 text-primary focus:ring-primary"> قیمت را اعلام نمی‌کنم؛ تماس بگیرید</label>@endif</div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">توضیحات</label><textarea name="description" rows="4" class="w-full rounded-lg border-slate-200 text-sm">{{ old('description', $listing->description) }}</textarea></div>
            <div x-data='imagePicker(@js($maxImageUploadMb), {{ max(0, 8 - $listing->images->count()) }})'><label class="mb-2 block text-sm font-bold text-neutral">افزودن تصاویر <span class="text-xs font-normal text-slate-400">حداکثر ۸ تصویر، هر تصویر {{ $maxImageUploadMb }} مگابایت</span></label><label class="flex cursor-pointer items-center gap-3 rounded-lg border-2 border-dashed border-primary/20 bg-primary-50/40 p-4 transition hover:border-primary/50"><span class="flex h-10 w-10 items-center justify-center rounded-lg bg-white text-primary shadow-sm"><x-heroicon-o-photo class="h-5 w-5" /></span><span class="text-xs font-bold text-slate-600">برای افزودن تصاویر کلیک کنید<input @change="select($event)" type="file" name="images[]" multiple accept=".jpg,.jpeg,.png,.webp" class="sr-only"></span></label><div x-show="previews.length" x-cloak class="mt-3 grid grid-cols-4 gap-2"><template x-for="preview in previews" :key="preview.url"><div class="overflow-hidden rounded-lg bg-slate-50 border border-slate-200"><img :src="preview.url" :alt="preview.name" class="h-20 w-full object-cover"><p x-text="preview.name" class="truncate px-1.5 py-1 text-[9px] text-slate-500"></p></div></template></div><div class="mt-2 flex items-center justify-between text-[10px] text-slate-400"><span x-show="previews.length" x-text="`${previews.length} تصویر جدید انتخاب شده`"></span><span>ظرفیت باقی‌مانده: {{ max(0, 8 - $listing->images->count()) }} تصویر</span></div><p x-show="invalid" x-text="message" class="mt-2 rounded-lg bg-error/10 px-3 py-2 text-xs font-bold text-error"></p></div>
            @if ($listing->images->isNotEmpty())<div><h2 class="mb-2 text-sm font-bold text-neutral">تصاویر فعلی</h2><div class="grid grid-cols-3 gap-2">@foreach ($listing->images as $image)<div class="relative"><img src="{{ asset('storage/'.$image->path) }}" alt="{{ $listing->title }}" class="h-24 w-full rounded-lg object-cover" loading="lazy" decoding="async"><form method="POST" action="{{ route('listings.images.destroy', [$listing, $image]) }}" class="absolute left-1 top-1">@csrf @method('DELETE')<button class="rounded-full bg-error px-2 py-1 text-[10px] font-bold text-white">حذف</button></form></div>@endforeach</div></div>@endif
            <div class="border-t border-slate-100 pt-4"><h2 class="font-black text-neutral">مشخصات گوشی</h2><div class="mt-4 space-y-3">@foreach ($attributes as $attribute) @php($saved = $listing->attributeValues->firstWhere('attribute_id', $attribute->id)) @php($current = $saved?->value_string ?? $saved?->value_integer ?? $saved?->value_decimal) <div><label class="mb-2 block text-sm font-bold text-neutral">{{ $attribute->name }} @if($attribute->pivot->is_required ?? $attribute->is_required)<span class="text-error">*</span>@endif</label>@if($attribute->type->value === 'boolean')<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="attributes[{{ $attribute->id }}]" value="1" @checked(old('attributes.'.$attribute->id, $saved?->value_boolean))> دارد</label>@elseif($attribute->type->value === 'multi_select') @php($selectedValues = old('attributes.'.$attribute->id, $saved?->value_json ?? []))<select multiple name="attributes[{{ $attribute->id }}][]" class="min-h-28 w-full rounded-lg border-slate-200 text-sm">@foreach($attribute->options ?? [] as $option)<option value="{{ $option }}" @selected(in_array($option, (array) $selectedValues, true))>{{ $option }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-400">برای انتخاب چند مورد، کلید Ctrl یا لمس چندگانه را استفاده کنید.</p>@elseif($attribute->type->value === 'select')<select name="attributes[{{ $attribute->id }}]" class="w-full rounded-lg border-slate-200 text-sm"><option value="">انتخاب کنید</option>@foreach($attribute->options ?? [] as $option)<option value="{{ $option }}" @selected(old('attributes.'.$attribute->id, $current) == $option)>{{ $option }}</option>@endforeach</select>@elseif(in_array($attribute->type->value, ['integer', 'decimal'], true))<input name="attributes[{{ $attribute->id }}]" type="number" step="{{ $attribute->type->value === 'decimal' ? '0.01' : '1' }}" value="{{ old('attributes.'.$attribute->id, $current) }}" class="w-full rounded-lg border-slate-200 text-sm">@else<input name="attributes[{{ $attribute->id }}]" type="text" value="{{ old('attributes.'.$attribute->id, $current) }}" class="w-full rounded-lg border-slate-200 text-sm">@endif</div>@endforeach</div></div>
            <button type="submit" class="mobile-button w-full bg-primary text-white hover:bg-primary-600">ذخیره و ارسال برای بررسی</button>
        </form>
    </section>
</x-app-layout>
