<x-admin-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-xl font-black text-neutral">داشبورد مدیریت</h1><span class="rounded-full bg-accent/10 px-3 py-1 text-xs font-bold text-accent">مدیر سیستم</span></div></x-slot>
    <section class="space-y-5 px-4 py-6">
        <div class="grid grid-cols-2 gap-3">@foreach ([['کاربران', $usersCount, 'text-info'], ['کل آگهی‌ها', $listingsCount, 'text-neutral'], ['تأییدشده', $approvedListingsCount, 'text-success'], ['ردشده', $rejectedListingsCount, 'text-error'], ['منقضی‌شده', $expiredListingsCount, 'text-slate-500']] as [$label, $value, $color])<div class="rounded-2xl bg-white p-4 shadow-sm"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-black {{ $color }}">{{ $value }}</p></div>@endforeach</div>
        <div class="grid grid-cols-2 gap-3"><a href="{{ route('admin.listings.index', ['status' => 'pending']) }}" class="rounded-2xl bg-warning/10 p-5 transition hover:-translate-y-0.5"><p class="text-sm font-bold text-neutral">در انتظار بررسی</p><p class="mt-2 text-3xl font-black text-warning">{{ $pendingListingsCount }}</p></a><a href="{{ route('admin.reports.index', ['status' => 'pending']) }}" class="rounded-2xl bg-primary/10 p-5 transition hover:-translate-y-0.5"><p class="text-sm font-bold text-neutral">گزارش‌های باز</p><p class="mt-2 text-3xl font-black text-primary">{{ $pendingReportsCount }}</p></a></div>
        <div class="rounded-2xl bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-black text-neutral">گزارش ثبت آگهی در ۷ روز گذشته</h2><p class="mt-1 text-xs text-slate-400">تعداد آگهی‌های جدید بر اساس تاریخ ثبت</p></div><span class="rounded-full bg-accent/10 px-3 py-1 text-xs font-bold text-accent">{{ $listingTrend->sum('count') }} آگهی</span></div><div class="mt-6 flex h-40 items-end justify-between gap-2 border-b border-slate-100"><div class="flex h-full flex-1 items-end justify-between gap-2">@php($maxTrend = max(1, $listingTrend->max('count')))<div class="contents">@foreach ($listingTrend as $day)<div class="flex h-full flex-1 flex-col items-center justify-end gap-2"><span class="text-[10px] font-bold text-slate-500">{{ $day['count'] }}</span><div class="w-full rounded-t-lg bg-primary transition-all" style="height: {{ max(8, (int) round(($day['count'] / $maxTrend) * 100)) }}%" title="{{ $day['date'] }}"></div><span class="text-[10px] text-slate-400">{{ $day['label'] }}</span></div>@endforeach</div></div></div></div>
        <div class="rounded-2xl bg-white p-4 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="font-black text-neutral">خلاصه وضعیت</h2><span class="text-xs text-slate-400">گزارش‌ها: {{ $resolvedReportsCount }} حل‌شده</span></div><div class="grid grid-cols-2 gap-2">@foreach ([['pending', 'در انتظار', 'bg-warning/10 text-warning'], ['approved', 'تأییدشده', 'bg-success/10 text-success'], ['rejected', 'ردشده', 'bg-error/10 text-error'], ['sold', 'فروخته‌شده', 'bg-info/10 text-info'], ['expired', 'منقضی‌شده', 'bg-slate-100 text-slate-500']] as [$key, $label, $classes])<a href="{{ route('admin.listings.index', ['status' => $key]) }}" class="rounded-xl {{ $classes }} p-3"><span class="block text-xs font-bold">{{ $label }}</span><strong class="mt-1 block text-xl">{{ $statusCounts->get($key, 0) }}</strong></a>@endforeach</div></div>
        <div class="rounded-2xl bg-white p-4 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="font-black text-neutral">آخرین فعالیت‌ها</h2><a href="{{ route('admin.listings.index') }}" class="text-xs font-bold text-primary">همه آگهی‌ها</a></div><div class="space-y-3">@forelse ($recentListings as $listing)<div class="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0 last:pb-0"><div class="min-w-0"><p class="truncate text-sm font-bold text-neutral">{{ $listing->title }}</p><p class="mt-1 truncate text-xs text-slate-500">{{ $listing->user->name }} · {{ $listing->brand->name }}</p></div><span class="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{{ $listing->status->label() }}</span></div>@empty<p class="text-sm text-slate-500">فعالیتی ثبت نشده است.</p>@endforelse</div></div>
    </section>
</x-admin-layout>
