<x-admin-layout>
    <x-slot name="header"><h1 class="text-xl font-black text-neutral">تنظیمات سیستم</h1></x-slot>
    <section class="space-y-4 px-4 py-6">
        @if ($errors->any())<div class="rounded-xl bg-error/10 p-3 text-sm font-bold text-error">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('admin.settings.update') }}" class="space-y-5 rounded-3xl bg-white p-5 shadow-sm">
            @csrf @method('PUT')
            <div><h2 class="font-black text-neutral">عنوان و ظاهر سایت</h2><p class="mt-1 text-xs leading-6 text-slate-500">این مقادیر در title صفحات و بخش‌های اصلی سایت استفاده می‌شوند.</p></div>
            <div><label class="mb-2 block text-sm font-bold text-neutral">عنوان سایت</label><input name="site_title" value="{{ old('site_title', $settings['site_title']) }}" required class="w-full rounded-xl border-slate-200 text-sm"></div>
            <div class="grid grid-cols-2 gap-2"><div><label class="mb-2 block text-sm font-bold text-neutral">پیشوند عنوان صفحات</label><input name="page_title_prefix" value="{{ old('page_title_prefix', $settings['page_title_prefix']) }}" class="w-full rounded-xl border-slate-200 text-sm"></div><div><label class="mb-2 block text-sm font-bold text-neutral">جداکننده عنوان</label><input name="title_separator" value="{{ old('title_separator', $settings['title_separator']) }}" required class="w-full rounded-xl border-slate-200 text-center text-sm"></div></div>
            <div class="border-t border-slate-100 pt-5"><h2 class="font-black text-neutral">آپلود و ثبت آگهی</h2><div class="mt-3"><label class="mb-2 block text-sm font-bold text-neutral">حداکثر حجم هر تصویر (MB)</label><input name="max_image_upload_mb" value="{{ old('max_image_upload_mb', $settings['max_image_upload_mb']) }}" required type="number" min="1" max="50" class="w-full rounded-xl border-slate-200 text-sm"><p class="mt-1 text-xs text-slate-400">مقدار پیش‌فرض: ۵ مگابایت</p></div><label class="mt-4 flex items-center gap-2 text-sm font-bold text-neutral"><input name="listings_enabled" value="1" type="checkbox" @checked(old('listings_enabled', filter_var($settings['listings_enabled'], FILTER_VALIDATE_BOOLEAN))) class="rounded border-slate-300 text-primary focus:ring-primary"> امکان ثبت آگهی جدید برای کاربران فعال باشد</label></div>
            <div class="border-t border-slate-100 pt-5"><h2 class="font-black text-neutral">اطلاعات پشتیبانی</h2><div class="mt-3 space-y-3"><div><label class="mb-2 block text-sm font-bold text-neutral">آدرس دفتر</label><textarea name="support_office_address" rows="3" class="w-full rounded-xl border-slate-200 text-sm">{{ old('support_office_address', $settings['support_office_address']) }}</textarea></div><div><label class="mb-2 block text-sm font-bold text-neutral">ایمیل پشتیبانی</label><input name="support_email" value="{{ old('support_email', $settings['support_email']) }}" type="email" class="w-full rounded-xl border-slate-200 text-sm" dir="ltr"></div><div><label class="mb-2 block text-sm font-bold text-neutral">شماره تماس پشتیبانی</label><input name="support_phone" value="{{ old('support_phone', $settings['support_phone']) }}" class="w-full rounded-xl border-slate-200 text-sm" dir="ltr"></div></div></div>
            <button class="mobile-button w-full bg-primary text-white hover:bg-primary-600">ذخیره تنظیمات</button>
        </form>
    </section>
</x-admin-layout>
