<x-admin-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h1 class="text-xl font-black text-neutral">مدیریت آگهی‌ها</h1><span class="text-xs text-slate-500">{{ $listings->total() }} مورد</span></div></x-slot>
    <section class="space-y-4 px-4 py-6">
        <form method="GET" class="grid grid-cols-2 gap-2 rounded-2xl bg-white p-3 shadow-sm"><input name="q" value="{{ request('q') }}" placeholder="عنوان یا نام کاربر" class="col-span-2 rounded-xl border-slate-200 text-sm"><select name="status" class="rounded-xl border-slate-200 text-sm"><option value="">همه وضعیت‌ها</option>@foreach ($statuses as $item)<option value="{{ $item }}" @selected($status === $item)>{{ \App\Enums\ListingStatus::from($item)->label() }}</option>@endforeach</select><button class="rounded-xl bg-neutral px-3 py-2 text-sm font-bold text-white">فیلتر</button></form>
        @forelse ($listings as $listing)
            <article class="rounded-2xl bg-white p-4 shadow-sm"><div class="flex gap-3">@if ($listing->primaryImage)<img src="{{ asset('storage/'.$listing->primaryImage->path) }}" alt="{{ $listing->title }}" class="h-16 w-16 shrink-0 rounded-xl object-cover">@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div><h2 class="font-bold text-neutral">{{ $listing->title }}</h2><p class="mt-1 text-xs text-slate-500">{{ $listing->user->name }} · {{ $listing->brand->name }} {{ $listing->phoneModel->name }}</p></div><span class="shrink-0 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-600">{{ $listing->status->label() }}</span></div><p class="mt-2 text-xs text-slate-500">{{ number_format($listing->price) }} تومان · {{ $listing->views_count }} بازدید</p></div></div><div class="mt-3 flex gap-2">@if ($listing->status->value !== 'approved')<form method="POST" action="{{ route('admin.listings.approve', $listing) }}">@csrf @method('PATCH')<button class="rounded-lg bg-success px-3 py-2 text-xs font-bold text-white">تأیید</button></form>@endif @if ($listing->status->value !== 'rejected')<form method="POST" action="{{ route('admin.listings.reject', $listing) }}" class="flex flex-1 gap-2"><input name="rejection_reason" required minlength="5" placeholder="دلیل رد" class="min-w-0 flex-1 rounded-lg border-slate-200 text-xs">@csrf @method('PATCH')<button class="rounded-lg bg-error px-3 py-2 text-xs font-bold text-white">رد</button></form>@endif</div></article>
        @empty
            <div class="rounded-2xl border border-dashed border-slate-200 bg-white p-8 text-center text-sm text-slate-500">آگهی‌ای با این فیلتر پیدا نشد.</div>
        @endforelse
        {{ $listings->links() }}
    </section>
</x-admin-layout>
