<x-admin-layout :title="'غرفه '.$user->name">
    <x-slot name="header">
        <div class="flex items-center gap-3">
            <a href="{{ route('admin.storefronts.index') }}" class="rounded-xl p-2 text-slate-500 transition hover:bg-slate-100" aria-label="بازگشت"><x-heroicon-o-arrow-right class="h-5 w-5" /></a>
            <div><p class="text-xs font-bold text-primary">مدیریت غرفه</p><h2 class="mt-1 text-xl font-black text-slate-900">{{ $user->name }}</h2><p class="mt-1 text-xs text-slate-400">{{ $user->mobile }}</p></div>
        </div>
    </x-slot>

    <section class="mx-auto max-w-3xl space-y-5">
        @if ($errors->any())<div class="rounded-2xl border border-error/20 bg-error/10 p-4 text-sm font-bold text-error" role="alert"><ul class="space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="rounded-2xl bg-primary p-5 text-white"><p class="text-xs font-bold text-primary-100">کنترل مدیریتی</p><h3 class="mt-1 text-lg font-black">غرفه {{ $store ? 'کاربر' : 'جدید' }}</h3><p class="mt-2 text-xs leading-6 text-white/70">مدیریت می‌تواند slug غرفه را تغییر دهد؛ این امکان برای کاربر عادی قفل است.</p></div>
        <form method="POST" action="{{ route('admin.storefronts.update', $user) }}" enctype="multipart/form-data" class="admin-card space-y-5 p-5">
            @csrf @method('PUT')
            <label class="flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-slate-50 p-4"><span><strong class="block text-sm font-black text-slate-800">فعال‌سازی غرفه</strong><small class="mt-1 block text-xs text-slate-400">صفحه عمومی غرفه برای دیگران نمایش داده شود.</small></span><input type="checkbox" name="store_enabled" value="1" @checked(old('store_enabled', $store?->is_enabled ?? true)) class="h-5 w-5 rounded border-slate-300 text-primary focus:ring-primary"></label>
            <div><label for="admin-store-name" class="mb-2 block text-sm font-bold text-slate-700">نام غرفه</label><input id="admin-store-name" name="name" value="{{ old('name', $store?->name ?? $user->name) }}" required class="w-full rounded-xl border-slate-200 text-sm focus:border-primary focus:ring-primary"></div>
            <div><label for="admin-store-slug" class="mb-2 block text-sm font-bold text-slate-700">آدرس انگلیسی غرفه</label><div class="flex items-center gap-2"><span class="rounded-xl bg-slate-100 px-3 py-3 text-xs text-slate-500" dir="ltr">/store/</span><input id="admin-store-slug" name="slug" value="{{ old('slug', $store?->slug) }}" dir="ltr" required class="min-w-0 flex-1 rounded-xl border-slate-200 text-sm focus:border-primary focus:ring-primary" placeholder="mobile-shop"></div><p class="mt-1 text-[11px] text-slate-400">فقط حروف انگلیسی کوچک، عدد و خط تیره.</p></div>
            <div x-data='storefrontLocation(@js(url("/locations/provinces")), @js(old("province_id", $store?->province_id)), @js(old("city_id", $store?->city_id)))' class="grid grid-cols-2 gap-3"><div><label for="admin-store-province" class="mb-2 block text-sm font-bold text-slate-700">استان</label><select id="admin-store-province" name="province_id" x-model="provinceId" @change="loadCities()" class="w-full rounded-xl border-slate-200 text-sm"><option value="">انتخاب استان</option>@foreach ($provinces as $province)<option value="{{ $province->id }}">{{ $province->name }}</option>@endforeach</select></div><div><label for="admin-store-city" class="mb-2 block text-sm font-bold text-slate-700">شهر</label><select id="admin-store-city" name="city_id" x-model="cityId" :disabled="!provinceId || citiesLoading" class="w-full rounded-xl border-slate-200 text-sm disabled:bg-slate-100"><option value="">انتخاب شهر</option><template x-for="city in cities" :key="city.id"><option :value="city.id" x-text="city.name"></option></template></select><p x-show="citiesLoading" class="mt-1 text-[11px] text-slate-400">در حال دریافت شهرها...</p></div></div>
            <div><label for="admin-store-logo" class="mb-2 block text-sm font-bold text-slate-700">لوگوی غرفه</label><input id="admin-store-logo" name="logo" type="file" accept=".jpg,.jpeg,.png,.webp" class="w-full rounded-xl border border-slate-200 p-2 text-sm"></div>
            <div><label for="admin-store-address" class="mb-2 block text-sm font-bold text-slate-700">آدرس فروشگاه</label><textarea id="admin-store-address" name="address" rows="3" class="w-full rounded-xl border-slate-200 text-sm">{{ old('address', $store?->address) }}</textarea></div>
            <div><label for="admin-store-phone" class="mb-2 block text-sm font-bold text-slate-700">تلفن تماس</label><input id="admin-store-phone" name="contact_phone" value="{{ old('contact_phone', $store?->contact_phone ?? $user->mobile) }}" dir="ltr" class="w-full rounded-xl border-slate-200 text-sm"></div>
            <div class="flex justify-end"><button class="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-black text-white transition hover:bg-primary-600"><x-heroicon-o-check class="h-5 w-5" />ذخیره تغییرات</button></div>
        </form>
    </section>
</x-admin-layout>
