<x-app-layout title="اعلان‌ها">
    <x-slot name="header">
        <div class="flex items-center justify-between gap-3"><div><p class="text-xs font-bold text-primary">به‌روزرسانی‌ها</p><h1 class="mt-1 text-xl font-black text-neutral">اعلان‌ها</h1></div>@if (auth()->user()->unreadNotifications()->exists())<form method="POST" action="{{ route('notifications.read-all') }}">@csrf @method('PATCH')<button class="inline-flex items-center gap-1.5 rounded-xl bg-primary/10 px-3 py-2 text-xs font-bold text-primary"><x-heroicon-o-check class="h-4 w-4" />خواندن همه</button></form>@endif</div>
    </x-slot>
    <section class="space-y-3 px-4 py-6">
        @if (session('status'))<div class="flex items-center gap-2 rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-sm font-bold text-success" role="status"><x-heroicon-o-check-circle class="h-5 w-5" />{{ session('status') }}</div>@endif
        @forelse ($notifications as $notification)
            @php($data = $notification->data)
            <article class="rounded-2xl {{ $notification->read_at ? 'bg-white ring-1 ring-slate-100' : 'border border-primary/20 bg-primary-50' }} p-4 shadow-sm"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl {{ $notification->read_at ? 'bg-slate-100 text-slate-400' : 'bg-primary text-white' }}"><x-heroicon-o-bell class="h-5 w-5" /></span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><h2 class="font-black text-neutral">{{ $data['title'] ?? 'اعلان سیستم' }}</h2>@if (! $notification->read_at)<span class="rounded-full bg-primary px-2 py-1 text-[10px] font-black text-white">جدید</span>@endif</div><p class="mt-1 text-sm leading-6 text-slate-600">{{ $data['message'] ?? '' }}</p>@if (! empty($data['reason']))<p class="mt-2 rounded-xl bg-white/70 p-2 text-xs text-slate-500">دلیل: {{ $data['reason'] }}</p>@endif<p class="mt-2 text-[11px] text-slate-400">{{ $notification->created_at?->diffForHumans() }}</p></div></div><div class="mt-3 flex items-center gap-2">@if (! empty($data['url']) && ($data['listing_available'] ?? true))<a href="{{ $data['url'] }}" class="rounded-lg bg-neutral px-3 py-2 text-xs font-bold text-white">مشاهده آگهی</a>@elseif (array_key_exists('listing_available', $data) && ! $data['listing_available'])<span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-500">آگهی دیگر در دسترس نیست</span>@endif @if (! $notification->read_at)<form method="POST" action="{{ route('notifications.read', $notification->id) }}">@csrf @method('PATCH')<button class="rounded-lg bg-white px-3 py-2 text-xs font-bold text-slate-600 ring-1 ring-slate-200">علامت خوانده‌شده</button></form>@endif</div></article>
        @empty
            <div class="rounded-3xl border border-dashed border-slate-200 bg-white p-10 text-center shadow-sm"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary-50 text-primary"><x-heroicon-o-bell class="h-7 w-7" /></span><h2 class="mt-4 font-black text-neutral">هنوز اعلانی ندارید</h2><p class="mt-2 text-sm leading-6 text-slate-500">وضعیت آگهی‌ها و پیام‌های مهم اینجا نمایش داده می‌شود.</p></div>
        @endforelse
        {{ $notifications->links() }}
    </section>
</x-app-layout>
