@php($systemOptions = app(\App\Services\SystemOptions::class))
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ $systemOptions->pageTitle($title ?? 'پنل مدیریت') }}</title>
        <meta name="theme-color" content="#111827">
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
        <link rel="apple-touch-icon" sizes="192x192" href="{{ asset('images/logo-192.png') }}">
        @vite(['resources/css/admin.css', 'resources/js/admin.js'])
    </head>
    <body class="font-sans antialiased">
        <div x-data="{ sidebarOpen: false }" class="min-h-screen">
            <div x-cloak x-show="sidebarOpen" x-transition.opacity class="fixed inset-0 z-40 bg-slate-950/60 lg:hidden" @click="sidebarOpen = false"></div>
            <aside class="fixed inset-y-0 right-0 z-50 flex w-72 translate-x-full flex-col bg-slate-900 text-white shadow-2xl transition-transform duration-300 lg:translate-x-0" :class="sidebarOpen ? 'translate-x-0' : 'translate-x-full'">
                <div class="flex h-20 items-center justify-between border-b border-white/10 px-6"><a href="{{ route('admin.dashboard') }}" class="flex items-center gap-3"><img src="{{ asset('images/logo-header.svg') }}" alt="Digistocki" class="h-10 w-10"><div><span class="block text-base font-black text-white">Digistocki</span><span class="text-[10px] font-medium text-slate-400">پنل مدیریت سامانه</span></div></a><button type="button" @click="sidebarOpen = false" class="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white lg:hidden" aria-label="بستن منو"><x-heroicon-o-x-mark class="h-5 w-5" /></button></div>
                <nav class="flex-1 space-y-1 overflow-y-auto px-4 py-6"><p class="mb-3 px-3 text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">نمای کلی</p><a href="{{ route('admin.dashboard') }}" class="admin-nav-link {{ request()->routeIs('admin.dashboard') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-squares-2x2 class="h-5 w-5" /> داشبورد</a><p class="mb-3 mt-7 px-3 text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">مدیریت محتوا</p><a href="{{ route('admin.listings.index') }}" class="admin-nav-link {{ request()->routeIs('admin.listings.*') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-rectangle-stack class="h-5 w-5" /> آگهی‌ها</a><a href="{{ route('admin.users.index') }}" class="admin-nav-link {{ request()->routeIs('admin.users.*') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-users class="h-5 w-5" /> کاربران</a><a href="{{ route('admin.reports.index') }}" class="admin-nav-link {{ request()->routeIs('admin.reports.*') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-flag class="h-5 w-5" /> گزارش‌ها</a><a href="{{ route('admin.brands.index') }}" class="admin-nav-link {{ request()->routeIs('admin.brands.*', 'admin.phone-models.*', 'admin.attributes.*') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-device-phone-mobile class="h-5 w-5" /> کاتالوگ گوشی</a><p class="mb-3 mt-7 px-3 text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">سیستم</p><a href="{{ route('admin.settings.edit') }}" class="admin-nav-link {{ request()->routeIs('admin.settings.*') ? 'admin-nav-link-active' : '' }}"><x-heroicon-o-cog-6-tooth class="h-5 w-5" /> تنظیمات</a><a href="{{ route('home') }}" class="admin-nav-link"><x-heroicon-o-arrow-top-right-on-square class="h-5 w-5" /> مشاهده سایت</a></nav>
                <div class="border-t border-white/10 p-4"><div class="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><div class="flex h-10 w-10 items-center justify-center rounded-full bg-primary font-black text-white">{{ mb_substr(auth()->user()->name, 0, 1) }}</div><div class="min-w-0"><p class="truncate text-sm font-bold text-white">{{ auth()->user()->name }}</p><p class="truncate text-xs text-slate-400">مدیر سیستم</p></div><form method="POST" action="{{ route('logout') }}" class="mr-auto">@csrf<button class="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white" aria-label="خروج"><x-heroicon-o-arrow-left-start-on-rectangle class="h-5 w-5" /></button></form></div></div>
            </aside>
            <div class="min-h-screen transition-all lg:mr-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-4 shadow-sm backdrop-blur sm:px-6 lg:px-8"><div class="flex items-center gap-4"><button type="button" @click="sidebarOpen = true" class="rounded-xl border border-slate-200 p-2 text-slate-600 hover:bg-slate-50 lg:hidden" aria-label="باز کردن منو"><x-heroicon-o-bars-3 class="h-5 w-5" /></button><div><p class="text-xs font-medium text-slate-400">خوش آمدید، {{ auth()->user()->name }}</p><h1 class="mt-1 text-lg font-black text-slate-900">{{ $title ?? 'پنل مدیریت' }}</h1></div></div><div class="flex items-center gap-2"><a href="{{ route('home') }}" class="hidden rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold text-slate-600 transition hover:border-primary/30 hover:bg-primary-50 hover:text-primary sm:inline-flex">بازگشت به سایت</a><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-primary"><x-heroicon-o-shield-check class="h-5 w-5" /></div></div></header>@if (session('status'))<div class="mx-4 mt-5 rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-sm font-bold text-success sm:mx-6 lg:mx-8">{{ session('status') }}</div>@endif @isset($header)<div class="px-4 pt-6 sm:px-6 lg:px-8">{{ $header }}</div>@endisset<main class="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">{{ $slot }}</main></div>
        </div>
    </body>
</html>
