<x-app-layout title="غرفه شما">
    <x-slot name="header"><div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-lg bg-primary-50 text-primary"><x-heroicon-o-building-storefront class="h-6 w-6" /></span><div><p class="text-xs font-bold text-primary">فروش حرفه‌ای‌تر</p><h1 class="mt-1 text-xl font-black text-neutral">غرفه شما</h1></div></div></x-slot>
    <section class="space-y-5 px-4 py-6">
        @if (session('status'))<x-flowbite-alert type="success">{{ session('status') }}</x-flowbite-alert>@endif
        @if ($errors->any())<x-flowbite-alert type="danger"><ul class="space-y-1">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-flowbite-alert>@endif
        <div class="rounded-lg bg-neutral p-5 text-white"><p class="text-xs font-bold text-primary-100">ویترین اختصاصی فروشنده</p><h2 class="mt-2 text-xl font-black">آگهی‌هایتان را یکجا نمایش دهید</h2><p class="mt-2 text-xs leading-6 text-white/65">آدرس غرفه فقط یک‌بار انتخاب می‌شود و پس از ایجاد، تغییر آن فقط از طریق مدیریت امکان‌پذیر است.</p></div>
        @if ($store?->is_admin_disabled)<div class="flex items-start gap-3 rounded-lg border border-warning/20 bg-warning/10 p-4 text-sm font-bold text-amber-900"><x-heroicon-o-shield-exclamation class="mt-0.5 h-5 w-5 shrink-0" /><span>غرفه شما توسط مدیریت غیرفعال شده است و تا زمان رفع این محدودیت قابل نمایش عمومی نیست.</span></div>@endif
        <form method="POST" action="{{ route('storefront.update') }}" enctype="multipart/form-data" class="space-y-5 rounded-lg bg-white p-5 shadow-sm border border-slate-200">
            @csrf @method('PUT')
            <label class="flex cursor-pointer items-center justify-between gap-4 rounded-lg border border-slate-100 bg-slate-50 p-4"><span><strong class="block text-sm font-black text-neutral">فعال‌سازی غرفه</strong><small class="mt-1 block text-xs text-slate-400">پس از فعال‌سازی، صفحه عمومی غرفه برای دیگران قابل مشاهده است.</small></span><input type="checkbox" name="store_enabled" value="1" @checked(old('store_enabled', $store?->is_enabled ?? false)) @disabled($store?->is_admin_disabled) class="public-check h-5 w-5 disabled:cursor-not-allowed disabled:opacity-50"></label>
            <div><label for="store-name" class="mb-2 block text-sm font-bold text-neutral">نام غرفه</label><input id="store-name" name="name" value="{{ old('name', $store?->name ?? auth()->user()->name) }}" class="block w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30" placeholder="مثلاً موبایل رضایی"></div>
            <div><label for="store-slug" class="mb-2 block text-sm font-bold text-neutral">آدرس انگلیسی غرفه</label><div class="flex items-center gap-2"><span class="shrink-0 rounded-lg bg-slate-100 px-3 py-3 text-xs text-slate-500" dir="ltr">/store/</span><input id="store-slug" name="slug" value="{{ old('slug', $store?->slug) }}" @disabled($store) dir="ltr" class="min-w-0 flex-1 rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30 disabled:bg-slate-100 disabled:text-slate-500" placeholder="mobile-rezaei"></div><p class="mt-1 text-[11px] text-slate-400">فقط حروف انگلیسی کوچک، عدد و خط تیره؛ حداقل ۳ کاراکتر.</p></div>
            <div x-data="storefrontLocation(@js(url("/locations/provinces")), @js(old("province_id", $store?->province_id)), @js(old("city_id", $store?->city_id)))" class="grid grid-cols-2 gap-2"><div><label for="store-province" class="mb-2 block text-sm font-bold text-neutral">استان</label><select id="store-province" name="province_id" x-model="provinceId" @change="loadCities()" class="public-select"><option value="">انتخاب استان</option>@foreach ($provinces as $province)<option value="{{ $province->id }}">{{ $province->name }}</option>@endforeach</select></div><div><label for="store-city" class="mb-2 block text-sm font-bold text-neutral">شهر</label><select id="store-city" name="city_id" x-model="cityId" :disabled="!provinceId || citiesLoading" class="public-select"><option value="">انتخاب شهر</option><template x-for="city in cities" :key="city.id"><option :value="city.id" x-text="city.name"></option></template></select><p x-show="citiesLoading" class="mt-1 text-[11px] text-slate-400">در حال دریافت شهرها...</p></div></div>
            <div><label for="store-logo" class="mb-2 block text-sm font-bold text-neutral">لوگوی غرفه</label><input id="store-logo" name="logo" type="file" accept=".jpg,.jpeg,.png,.webp" class="public-file"></div>
            <div><label for="store-address" class="mb-2 block text-sm font-bold text-neutral">آدرس فروشگاه</label><textarea id="store-address" name="address" rows="3" class="block w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30">{{ old('address', $store?->address) }}</textarea></div>
            <div><label for="store-phone" class="mb-2 block text-sm font-bold text-neutral">تلفن تماس</label><input id="store-phone" name="contact_phone" value="{{ old('contact_phone', $store?->contact_phone ?? auth()->user()->mobile) }}" dir="ltr" class="block w-full rounded-lg border border-slate-200 bg-slate-50 text-sm text-neutral shadow-sm transition focus:border-primary focus:ring-2 focus:ring-primary/30"></div>
            <button class="mobile-button w-full bg-primary text-white hover:bg-primary-600"><x-heroicon-o-check class="h-5 w-5" />ذخیره اطلاعات غرفه</button>
        </form>
    </section>
</x-app-layout>
